### ISSUE TITLE
add french how-to-use to original how-to-use

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#103]
Using markdown, allow people to click to french version

**Comment by njr2128** [comment]
@Pantagrueliste, please give me a line in French that I can add to the English version that says something like: "Want to read this in French? Click here!" but in a way that seems appropriate

**Comment by Pantagrueliste** [comment]
Cliquez ici pour la version française

**Comment by njr2128** [comment]
Merci!

**Comment by njr2128** [comment]
done
