### ISSUE TITLE
addition of bib keys to bibliography.md

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#106]
### Final version to be added to bibliography text - changes in bold:

Bibliography (the proposed additional text is highlighted)
The Bibliography compiles references, texts, and authors cited in the manuscript, the editorial comments, and the glossary. 

**The Glossary uses short bibliographic keys instead of full citations. The keys usually combine author name and year of publication, or use an acronym such as OED for Oxford English Dictionary or DMF for _Dictionnaire du Moyen Français_. Search Glossary keys by acronym or author name.**

This bibliography includes detailed references for primary sources cited in the manuscript, however, they may not be the exact edition to which the manuscript refers. They include more widely available editions from prominent publishers in the sixteenth century (Robert and Henri Estienne, the Aldine press, Christophe Plantin, Hieronymus Froben, Johannes Herwagen, etc). Other possible editions can be found in the Universal Short Title Catalogue and similar resources.

The bibliographic databases are available as BibTeX and html, downloadable from the Project’s GitHub repository.

### Also add the following keys to their citations, using the form:
[DMF2015] citation

1. COT1611
2. DAF2018
3. TLFi2019
4. OED
5. DMF

**Comment by Pantagrueliste** [comment]
done
