### ISSUE TITLE
Create "coming soon" page

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#109]
For work-in-progress and other resources to come

**Comment by Pantagrueliste** [comment]
first draft uploaded.

**Comment by njr2128** [comment]
done: https://github.com/cu-mkp/edition-webpages/blob/master/docs/resources/coming-soon.md

Was added to Resources/Overview as well as its own page in the menu structure.

The only outstanding item is to add to homepage by Nick - separate issue in making-and-knowing-edition
