### ISSUE TITLE
remove all ">" in bullets from dictionaries page

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#115]
In https://github.com/cu-mkp/edition-webpages/blob/master/docs/resources/dictionaries.md, there are additional ">" characters added between each of the bullets, resulting in very large indentation spaces between the bullets and the text in the rendered wedpage.

These need to be removed in order to match other pages that contain bullets

**Comment by thuchacz** [comment]
Done. See pull request [https://github.com/cu-mkp/edition-webpages/pull/116](https://github.com/cu-mkp/edition-webpages/pull/116)

@njr2128 , please merge and close this issue.

**Comment by njr2128** [comment]
Done
