### ISSUE TITLE
Review use of bulleted lists in webpages

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/edition-webpages#13]
E.g. make sure (most) lists don't have more than two levels of indentation, and that the first level does not need a bullet.

**Comment by TillmannTaape** [comment]
E.g. How to use ➛ searching –– remove bullets and instead bold first few key words of each item?

**Comment by TillmannTaape** [comment]
E.g. How to use ➛ navigation-- bulleted list has too many levels, and too much indentation to the right.

**Comment by njr2128** [comment]
done
