### ISSUE TITLE
update m-k-project.md

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#14]
@tcatapano , for some reason, https://github.com/cu-mkp/edition-webpages/blob/master/docs/about/m-k-project.md did not get re-converted from GD to .md - it is still a version from about a month ago.

Can you run this file through pandoc and upload: https://drive.google.com/open?id=1gloz-nDvDwB23y04_K6j-FJazk_9PggODzRuylrlDmY?

Thank you!

**Comment by tcatapano** [comment]
I ended up just pasting the new content in rather than convert with pandoc. @njr2128 could you fine tune as you see fit. Also, note that the iframe seems a little big. We may want to adjust its settings.

**Comment by njr2128** [comment]
great, thank you!
Will do
