### ISSUE TITLE
Update how-to-use pages after redesign

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#180]
After the redesign is implemented, both how-to-use pages (EN and FR) need to be updated to reflect the new look and to reflect any navigation changes with the introduction of the side navigation bar.

Since these major changes are necessary, I am combining any other outstanding how-to-use-page-related issues here in one place.

# Changes to be made:

## Screenshots
Create new screenshots to reflect the site's new look

## Navigation
Revise any language or instructions regarding the site's navigation (now that we have the side navigation bar and a different layout)

## Essay Lightbox
https://github.com/cu-mkp/edition-webpages/issues/112
PROPOSED LANGUAGE:
In any essay, click on an image to view it at full size in a pop-out lightbox. Close the lightbox by clicking either on the "X" in the upper right-hand corner or outside of the image itself.

PROPOSED PLACEMENT:
How to Use, insert after:
"In any essay, click on the folio numbers contained in the text to view that manuscript page (return by clicking the back arrow in your browser)." and before "The Bibliography"

## Essays search
https://github.com/cu-mkp/edition-webpages/issues/132
Update how-to-use about the fact that phrase-level searching does not function for the essays.

## Glossary
https://github.com/cu-mkp/edition-webpages/issues/121
This issue was opened over a year ago and it is possible that it has already been completed. Check to see if information about glossary's changes to anatomy of a glossary entry (i.e., the order of elements) matches what appears in the glossary

## Misc. Language Edits
https://github.com/cu-mkp/edition-webpages/issues/132
Delete "The" in "The Bibliography.

## How-to-use Video [to be done separately from this issue]
https://github.com/cu-mkp/edition-webpages/issues/90
Keeping this issue open and separate as it is a big enough task on its own and is a different sort of task than editing the page itself. Mentioning here just so that the list is complete.

**Comment by njr2128** [comment]
Outstanding to do: update the FR version to match the EN version, which should be done by someone other than me. The screenshots are all updated and I have added the two additional search screenshots where they should go in the FR version, but without the language that should accompany them

**Comment by ps2270** [comment]
New screenshots appear huge in comparison to images that were already in
the page. They need to be reduced in size.

**Comment by njr2128** [comment]
Done
