### ISSUE TITLE
bibliography sidebar links not working

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/edition-webpages#181]
per comments from @njr2128 in GoogleDocs and email:

```
Bibliography - https://github.com/cu-mkp/edition-webpages/issues/177 
Add clickable side menu headers for: 
## Sources Cited in Ms. Fr. 640 and Editorial Comments
### Primary Sources 
### Secondary Sources
## Sources Cited in the Glossary
Need to check json file - right now, the menu headers are just: primary sources, secondary sources, sources cited in the glossary
“Sources cited in the glossary” does not take you anywhere when clicked

looks like the targets for the sidebar item links are not correct:

```

https://github.com/cu-mkp/edition-webpages/blob/d3bef3e0e4e48d67c3a86af2f3fd07ba20d3c891/menu-structure.json#L239-L248

It looks like the "id" field is the url of the corresponding section headings on the bibliography page. Only the one for "Secondary Sources" has the correct section heading url (which is derived from the section heading text)

"Primary Sources" should have id of "primary-sources"
"Sources Cited in the Glossary" should have id of "sources-cited-in-the-glossary"

**Comment by njr2128** [comment]
Terry fixed as part of commit 5efd167abc5a0f037958844c51fb9975fdda5f94
