### ISSUE TITLE
turn off github pages for repo

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/edition-webpages#186]

**Comment by tcatapano** [comment]
Set source to "None" as per https://docs.github.com/en/pages/getting-started-with-github-pages/unpublishing-a-github-pages-site. Github pages settings page says it is disabled, but it is still showing "Active" on the repo home page. Perhaps it takes time to be fully removed?

**Comment by njr2128** [comment]
The previous actions partially completed the task but more was needed to fully remove all mention and components/associations of github pages. 

On homepage of repo, "Environment" was still "Active" and there was still a link under the "About" details.

Deleted the repo URL under "About".
Also. under repo settings, deleted the github pages environment under "Environments".

This has now completely removed any github pages stuff
