### ISSUE TITLE
revamp of "Overview of Resources"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#22]
See GD doc **2020-01-17+24_editionwebpages-notes**

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Move List of Entries content from bottom to top
     - Add category pie chart?
     - Remove list of semantic tags
     - Thoughts about table?
- Add relative links to each heading (ie Glossary should link to the glossary)
- Field Notes - add language about link coming soon
- Remove “how to use” language
     - If info is not in how-to-use page, copy and paste content into a new issue and assign to NJR (eg under Glossary)
- Move info about Editorial Comments to About the Manuscript
- Add relative links to PHS essay
- Ways to add images?
- Remove “iterative” in the sentence that begins:
     - “To transform the pages of Ms. Fr. 640 into digital text, the Making and Knowing Project began transcribing…”
- The Glossary: “It contains” — rename “It includes” and condense the list that follows:
     - meaning(s) of words according to context
     - bibliographic references for those meanings
     - alternative spellings and modern spelling
     - language or dialect of origin
- Research Essays
     - “Essays composed by students as part of their involvement in the Making and Knowing Project laboratory seminars ask, for the most part, historical questions about the manuscript and its context.”
     - Copy list of essay category descriptions from the revised version in current How to use
     - Shorten this section, eg info about academic commons?
          - NJR comment: we have no other place that explains the essays. For now, all info should go here for lack of a better place. Thus, if long, I think we should live with it for now
- Change flickr link to the ALBUMS link and hyperlink some text instead of full URL
- List of Entries - descriptions can be shortened by removing verbs

**Comment by TillmannTaape** [comment]
All done, notes updated in GDoc; closing here.

**Comment by TillmannTaape** [comment]
Tested all live links (dictionaries and PHS essays not live yet)
