### ISSUE TITLE
revamp of Principles (landing and each individual page)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#24]
See GD doc **2020-01-17+24_editionwebpages-notes**

LANDING PAGE

- MAKE NEW PAGE FOR DICTIONARIES (which is currently an appendix to P of Translation
      - Add link to overview page and P of Translation
- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Add short statements under each link
- Add reference to PHS essay about the edition?

**Comment by njr2128** [comment]
PRINCIPLES OF TRANSCRIPTION

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- TYPOS
- Clement Godbarge with an accent
- Should “Protocol” be capitalized?

**Comment by njr2128** [comment]
PRINCIPLES OF TRANSLATION

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Remove appendix and add link to new separate page instead
- TYPOS
- “hundred of variations” should be “hundreds of variations”
- “here are sometimes word fragments of words”
- Clement Godbarge with an accent

**Comment by njr2128** [comment]
PRINCIPLES OF ENCODING

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Check font size change in second paragraph
- missing period after the sentence following the table
- Inconsistent font size in the table
- in case they are useful to users of the Edition.
- lb - used only in transcription - do we need to acct for structural lb in trans?

**Comment by TillmannTaape** [comment]
All DONE – see comments in GDoc.

Outstanding problem: links to Philipp's add-ons not working.
