### ISSUE TITLE
revamp of "About > The Manuscript"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#25]
See GD doc **2020-01-17+24_editionwebpages-notes**

Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
Content from the previous “The Text: Overview and About”
Add Editorial Comments (take from Overview of Resources)

**Comment by TillmannTaape** [comment]
Latest text for editorial comments:

## Editorial Comments

Editorial Comments, marked by a red asterisk in the
transcriptions and translation, clarify structural
features of the text (such as deletions, additions, marks, etc.),
definitions of obscure terms, translation decisions, and provide additional information.

A full list can be accessed by selecting
“Research and Resources” → “List of Editorial Comments.”

**Comment by njr2128** [comment]
WORK FROM PHS document, About_About the Manuscript_2020-01-24

**Comment by Pantagrueliste** [comment]
The editorial comments bit refers to a menu called "List of Editorial Comments" in the "Research and Resources" menu.  I can't link these pages as I don't find them. Are we still having them? @njr2128

**Comment by ps2270** [comment]
fix Marking and knowing title

**Comment by ps2270** [comment]
Dyon: ann_318_ie_19
Camps: ann_331_ie_19
Smith, making the Edition: ann_329_ie_19
Smith, Introduction  ann_300_ie_19
M Smith, Codicology, ann_326_ie_19
Godbarge, ann_301_ie_19
catapano/Rosenkranz  ann_310_ie_19

**Comment by ps2270** [comment]
done!
