### ISSUE TITLE
Add content to "categories"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#29]
Information about List of Entries to be moved here

Add pie chart and table

Link to List of Entries page

Anything else?

**Comment by njr2128** [comment]
consider making first table of category descriptions into a list instead (and remove percentages)

**Comment by Pantagrueliste** [comment]
can we convert the _Overview of Manuscript's Contents_ into a MD table?

**Comment by njr2128** [comment]
> can we convert the _Overview of Manuscript's Contents_ into a MD table? Image is blurry on retina screens. And perhaps also convert the diagram in SVG to include it in an iframe.

The overview table had been a md table but then no colors can be used. 
I agree with you about both points, but it will have to be in future releases

**Comment by njr2128** [comment]
outstanding question moved to #76

Done.
