### ISSUE TITLE
Add info on glossary to How to Use

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/edition-webpages#30]
Text from "Overview" that should go into how to use, re glossary:

"
The Glossary is a record of distinctive terms used in the manuscript
which was compiled in the transcription and translation of the text.

It includes:

  - meaning(s) of words according to context
  - bibliographic references for those meanings
  - alternative spellings and modern spelling
  - language or dialect of origin

Sample entry:

 Acoustrer (mod. accoutrer): v. to prepare \[COT1611\]
    
      - In this entry, the word as it appears in Ms. Fr. 640 is followed by its modern spelling, its part of speech, and its meaning in English. The key in square brackets indicates the source of the definition, as listed in the [Bibliography](/#/content/research+resources/bibliography).

The glossary can be navigated by clicking on the relevant letter, or by
using the dedicated search box to find a particular word (the search
will return modern and alternative contemporary spellings as well as
head words).

**A note on early modern spelling:** if a word from the manuscript text
returns no hits in the glossary, try searching for a shorter string
(e.g. the beginning of the word) or a different spelling. The
author-practitioner’s early modern French shows little standardization,
and while the glossary includes common spelling variants, the list is
not exhaustive. Common variations are:

  - double vs. single consonant, as in *plate* vs. *platte*

  - homonyms, e.g. aiguille, esguille; alun, alum, alung"

**Comment by njr2128** [comment]
done
