### ISSUE TITLE
upcoming features to include in overview page

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/edition-webpages#31]
Include a brief description of upcoming features we will include in the website over the coming months, such as:

- improved bibliography
- ...

**Comment by TillmannTaape** [comment]
Bibliography and Field notes have their own dedicated sections. Field notes as indicates as "coming soon", and the Bibliography description has a note to say that the references from all essays will eventually be added.

So Bib and field notes are covered. Any other forthcoming features that we would put in a dedicated section at the bottom?

**Comment by Pantagrueliste** [comment]
Adaptive design (mobile compatibility)

**Comment by thuchacz** [comment]
Additional essays
Faceting of entries list by entry category

NB: we can always update this page with additional additional features in the future :)

**Comment by njr2128** [comment]
completed and deployed: https://edition640.makingandknowing.org/#/content/resources/coming-soon
