### ISSUE TITLE
revamp of "About > contact"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#46]
See GD doc **2020-01-17+24_editionwebpages-notes**

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Create dedicated email for bugs?
- Images?
- Add social media contacts/links (FB, Flickr, Twitter)
- link to CU policies

**Comment by njr2128** [comment]
social media - copy the snippet at the top of each specific icon that looks something like `<i class="fab fa-facebook"></i>

facebook icons: https://fontawesome.com/icons?d=gallery&q=facebook

https://fontawesome.com/icons?d=gallery&q=twitter

youtube: https://fontawesome.com/icons?d=gallery&q=youtube

flickr: https://fontawesome.com/icons/flickr?style=brands

listserve: 
https://fontawesome.com/icons/mailchimp?style=brands
or
https://fontawesome.com/icons?d=gallery&q=email

**Comment by njr2128** [comment]
done

**Comment by thuchacz** [comment]
Done.

The only outstanding issue: the icon for the "donate to the project" link is not rendering.
