### ISSUE TITLE
Anchor Menu

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/edition-webpages#66]
In long pages, like the [bibliography](https://github.com/cu-mkp/edition-webpages/tree/master/docs/research%2Bresources/bibliography.md), I recommend adding a brief summary of the page contents with anchors, in order to facilitate navigation. 

markdown code for an anchor is:
```
<a id="AnchorName"></a> 
```
to link this anchor: 
```
[LinkText](#AnchorName)
```
or use the heading name.

You can also create a "go back to menu" link with the same code.

**Comment by Pantagrueliste** [comment]
@NickLaiacona making anchors with GitHub Flavored Markdown (GFM) does not work on the edition. What Markdown variant is our website using?  CommonMark, Pandoc, Litedown, R Markdown, Markdown extra... ?

**Comment by NickLaiacona** [comment]
We are using GFM. The problem isn't with the MD parsing, but the server-less architecture of the site. Navigation within the site makes use of the anchor syntax (# sign).  So we will need to add a feature to the MK Edition to handle anchor links in the content pages.

**Comment by Pantagrueliste** [comment]
Ok, thanks! I'll delete the anchors.
