### ISSUE TITLE
about - sponsors edits

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#69]
- group CU

- move Ferguson to end ("prize" --> "award")

- CHF - (now Science History Institute)

- Gerda Henkel - add "grant AZ..." & Scholar**s** 2017-20

- fix NSF grant numbers

**Comment by ps2270** [comment]
Change opening paragraph to:
Sponsors
_Secrets of Craft and Nature in Renaissance France_ would not have been possible without a wide network of supporters. The Making and Knowing Project gratefully acknowledges the support of countless individuals and collaborators from institutions around the world. The Project is especially grateful for the grants and gifts that underwrote the creation of the Edition:

**Comment by ps2270** [comment]
I made some changes, and it's done now.

**Comment by ps2270** [comment]
Add ISERP as Columbia affiliate to sponsor page

**Comment by njr2128** [comment]
Completed already yesterday or the day before. See:
https://github.com/cu-mkp/edition-webpages/blob/master/docs/about/sponsors.md
